mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    #url(r'^nbrb', include('nbrb.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('nbrb.urls')),
]

nbrb/urls.py
from django.conf.urls import url


from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^exrates', views.exchange_rates, name='exrates'),
    url(r'^priceMetals', views.price_metals, name='priceMetals'),
    url(r'^(?P<abbreviation>[A-Z]{3})', views.info_currency, name='info_currency'),
    url(r'^(?P<name>.+)', views.info_metal, name='info_metal')
]

nbrb/models.py
from django.db import models


class ExchangeRates(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField()
    rate = models.FloatField()
    scale = models.IntegerField()
    abbreviation = models.CharField(max_length=4)


class IngotRates(models.Model):
    ingot_name = models.CharField(max_length=15)
    date = models.DateField()
    value = models.FloatField()

nbrb/forms.py
from django import forms
import datetime


TODAY = datetime.datetime.today()
START_DAY = (TODAY - datetime.timedelta(days=31)).strftime('%Y-%m-%d')
END_DATE = TODAY.strftime('%Y-%m-%d')


class DateForm(forms.Form):
    start_date = forms.DateField(initial=START_DAY, label='Дата начала периода')
    end_date = forms.DateField(initial=END_DATE, label='Дата конца периода')

nbrb/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from .models import ExchangeRates
from .models import IngotRates
from .currency_info import currency_info
from .forms import DateForm
from .ingot_info import ingot_info


NUMBER_OF_METALS = 4
NUMBER_OF_CURRENCY = 26


def index(request):
    template = loader.get_template('nbrb/index.html')
    return HttpResponse(template.render())


def price_metals(request):
    list_daily_price_ingots = IngotRates.objects.order_by('-pk')[:NUMBER_OF_METALS]
    template = loader.get_template('nbrb/price_metals.html')
    context = {
        'list_daily_price_ingots': list_daily_price_ingots,
        'date': list_daily_price_ingots[0].date
    }
    return HttpResponse(template.render(context))


def exchange_rates(request):
    list_daily_exrates = ExchangeRates.objects.order_by('-pk')[:NUMBER_OF_CURRENCY]
    template = loader.get_template('nbrb/exrates.html')
    context = {
        'list_daily_exrates': list_daily_exrates,
        'date': list_daily_exrates[0].date
    }
    return HttpResponse(template.render(context))


def info_currency(request, abbreviation):
    template = loader.get_template('nbrb/info_valute.html')
    context = {
        'img': currency_info[abbreviation]['img'],
        'info': currency_info[abbreviation]['info']
    }
    return HttpResponse(template.render(context))


def info_metal(request, name):
    if request.method == 'POST':
        form = DateForm(request.POST)
        if form.is_valid():
            list_daily_price_ingots = IngotRates.objects.filter(ingot_name=name)
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            list_of_metal = []
            for ingot in list_daily_price_ingots:
                if ingot.date >= start_date and ingot.date <= end_date:
                    list_of_metal.append(ingot)

            context = {
                'list_of_metal': list_of_metal,
                'form': form,
                'info': ingot_info[name],
                'name': name
            }
            return render(request, 'nbrb/info_metal.html', context)

    else:
        form = DateForm()
        context = {
            'text': 'Введите промежуток дат, за который нужно вывести цены',
            'form': form,
            'info': ingot_info[name],
            'name': name
        }
        return render(request, 'nbrb/info_metal.html', context)

nbrb/templates/nbrb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="../static/nbrb/FlatUI/dist/css/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/nbrb/FlatUI/dist/css/flat-ui.css" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
 <style>
      body {
        min-height: 500px;
      }

      .navbar-static-top {
        margin-bottom: 19px;
      }
 </style>

    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
          </button>
          <a class="navbar-brand" href="/">NBRB</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/exrates/">Цены на валюты</a></li>
            <li><a href="/priceMetals/">Цены на металлы</a></li>
          </ul>
        </div>
      </div>
    </div>

  <div class="container">

      <div class="jumbotron">
        <p>{% block content %}{% endblock %}</p>
        </p>
      </div>

  </div>
</body>
</html>

nbrb/templates/nbrb/exrates.html
{% extends "nbrb/base.html" %}
{% block title %}Цены на валюты{% endblock %}

{% block content %}
<h5>Курс белорусского рубля по отношению к иностранным валютам:</h5>
Последнее обновление данных: {{ date }}
<br>
<div class="table-responsive">
    <table class="table">
    <thead>
    <tr>
    <th>Код валюты:</th>
    <th>Название валюты:</th>
    <th>Кол-во единиц</th>
    <th>Официальный курс валюты:</th>
        </tr>
    </thead>
    <tbody>
    {% for rate in list_daily_exrates %}
    <tr>
        <td>{{ rate.abbreviation }}</td>
        <td><a href="/{{ rate.abbreviation }}/">{{ rate.name }}</a></td>
        <td>{{ rate.scale }}</td>
        <td>{{ rate.rate }}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
</div>
{% endblock %}

nbrb/templates/nbrb/index.html
{% extends "nbrb/base.html" %}
{% block title %}Главная{% endblock %}
{% block content %}
<h3>NBRB script</h3>
<p>Данное приложение ежедневно обновляет данные курса валют и цен на драгоценные металлы
    Национального Банка Республики Беларусь.
    Приложение написано с помощью python3 и веб-фреймворка django.
</p>
{% endblock %}

nbrb/templates/nbrb/info_metal.html
{% extends "nbrb/base.html" %}
{% block title %}Информация о металле{% endblock %}
{% block head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script>
            $(function() {
                    $( "#id_start_date" ).datepicker({
                            dateFormat: "yy-mm-dd",
                            defaultDate: "-31",
                            maxDate: "+0d",
                            minDate: "2017-01-01",
                            changeMonth: true,
                            numberOfMonths: 1,
                            onClose: function( selectedDate ) {
                                    $( "#id_start_date" ).datepicker( "option", selectedDate );
                            }
                    });
            });
            $(function() {
                    $( "#id_end_date" ).datepicker({
                            dateFormat: "yy-mm-dd",
                            maxDate: "+0d",
                            changeMonth: true,
                            numberOfMonths: 1,
                            onClose: function( selectedDate ) {
                                    $( "#id_end_date" ).datepicker( "option", selectedDate );
                            }
                    });
            });
    </script>
{% endblock %}
{% block content %}
    <h5>{{ name }}</h5>
    <br>
    <p>{{ info }}</p>

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Показать" class="btn btn-primary"/>
    </form>
    {% if text %}
    {{ text }}
    {% elif list_of_metal %}
    <h6>Цены за выбранный промежуток дат:</h6>
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
            <th>Дата:</th>
            <th>Цена за 1 грамм:</th></tr>
            </thead>
            <tbody>
            {% for rate in list_of_metal %}
            <tr>
                <td>{{ rate.date }}</td>
                <td>{{ rate.value }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <p>Неправильно введена дата!</p>
{% endif %}

{% endblock %}

nbrb/templates/nbrb/info_valute.html
{% extends "nbrb/base.html" %}
{% block title %}Информация о валюте{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="row">
    <div class="col-1-md-2 col-md-offset-4">
    <img src="{% static 'nbrb/images/' %}{{ img }}.svg" class="img-rounded img-responsive" width="300" height="200" />
    </div>
    <br>
    <p>{{ info }}</p>
</div>
{% endblock %}

nbrb/templates/nbrb/price_metals.html
{% extends "nbrb/base.html" %}
{% block title %}Цены на металлы{% endblock %}
{% block content %}
<h5>Цены на драгоценные металлы в виде банковских слитков:</h5>
<p>Последнее обновление данных: {{ date }}</p>
<div class="table-responsive">
    <table class="table">
    <thead>
    <tr>
    <th>Название металла:</th>
    <th>Цена за 1г.</th>
    </tr>
    </thead>
    <tbody>
    {% for rate in list_daily_price_ingots %}
        <tr>
        <td><a href="/{{ rate.ingot_name }}">{{ rate.ingot_name  }}</a></td>
        <td>{{ rate.value }}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
</div>
{% endblock %}